workers:
    tailwind:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch']

    scheduler:
        cmd: [ 'symfony', 'console', 'messenger:consume', 'scheduler_default' ]
        watch: [ 'config', 'src' ]
